### ISSUE TITLE
Multiple expiry tasks

### ISSUE THREAD

**Issue by boy0001** [IntellectualSites/PlotSquared#1056]
@AeSix
Would be useful to allow for multiple expiry conditions i.e. copy the block in the config to create a new set of conditions.

If a plot meets any of the conditions it is cleared.

**Comment by AeSix** [comment]
This sounds like a wonderful idea! :D

**Comment by MattBDev** [comment]
@AeSix Then why not click the react button to make it happen faster ;)

**Comment by darknightcore** [comment]
It is also usefull to configure the time before a plot gets cleared, for each world.
e.g. auto clear:
world: 30 days
world_build: no auto clear

**Comment by boy0001** [comment]
Added
```YML
auto-clear:
  task1:
    threshold: 1
    confirmation: true
    days: 7
    worlds: 
    - "*"
    calibration:
      variety: 0
      variety-sd: 0
      changes: 0
      changes-sd: 1
      faces: 0
      faces-sd: 0
      data-sd: 0
      air: 0
      air-sd: 0
      data: 0
```
