### ISSUE TITLE
Plot Expiry SOE

### ISSUE THREAD

**Issue by manuelgu** [IntellectualSites/PlotSquared#1292]
# Bug report

**Description of the problem:**
A StackOverflow exception is being thrown shortly after the server has started. Total plots about 4000, majority of them expired.

http://hastebin.com/calufogare.avrasm

**How to replicate**:
Set config values to the following and enable plot expiry.

```
auto-clear:
  task1:
    threshold: -1
    required-plots: -1
    confirmation: true
    days: 90
    worlds:
    - "*"
    # See: https://github.com/IntellectualSites/PlotSquared/wiki/Plot-analysis
    calibration:
      variety: 0
      variety-sd: 0
      changes: 0
      changes-sd: 1
      faces: 0
      faces-sd: 0
      data-sd: 0
      air: 0
      air-sd: 0
      data: 0
```
