### ISSUE TITLE
Question about plot prizes

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualSites/PlotSquared#1310]
Hey there,

actually I am not quite deep into Java or Javascript so I basically am unsure about the dynamic price feature.
The wiki says

```
  prices:
    # Can use javascript for dynamic prices
    claim: 100*{arg}+50
    sell: 100
    merge: 100
```

If I understand this correctly the first plot will charge (with economy true of course) 100 credits, the second 150, the 3rd 200 and so on, right?

So if for example set my plot prices to this
```
      prices:
        claim: 25000*{arg}+25000
        sell: 20000*{arg}+20000
        merge: 0.0
```
it would charge the player for the first plot 25000 credits, for the second 50000, for the 3rd 75000 and vice versa for selling.

Is this feature in the 3.4.4 branch already available or is this in 3.4.5?

Thanks for taking a look.
