### ISSUE TITLE
Plot Purge, question.

### ISSUE THREAD

**Issue by SliderKP** [IntellectualSites/PlotSquared#1361]
He wanted to know how should put in my config purge to clear all plots that have claimeado and do not have even a single change , as it should ? I mean that if the plot is 100 % as the grant , it is cleared by purging from already thank you very much . I realize this question in this way since reading fails to understand the wiki

**Comment by boy0001** [comment]
Default configuration without confirmation will do that, just need to enable it in the config
```YML
enabled-components:
  # Expiry will clear old or simplistic plots
  plot-expiry: true

auto-clear:
  task1:
    threshold: 1
    required-plots: -1
    confirmation: false
    days: 7
    worlds: 
    - "*"
    # See: https://github.com/IntellectualSites/PlotSquared/wiki/Plot-analysis
    calibration:
      variety: 0
      variety-sd: 0
      changes: 0
      changes-sd: 1
      faces: 0
      faces-sd: 0
      data-sd: 0
      air: 0
      air-sd: 0
      data: 0
```
