### ISSUE TITLE
Nukkit PlotSquared with bridge generator

### ISSUE THREAD

**Issue by NycuRO** [IntellectualSites/PlotSquared#1398]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:

**Description of the problem:**
If you use bridge in nukkit , using /p or /plot auto or /p , /p home , you teleported in fence.
**How to replicate**:
Create bridge in nukkit with fence like photo bukkit site. ( Hybrid generator ).
Use /p auto or /p claim and /p home.
Now you are blocked in fence.

I know how fix. In /p auto : you can add teleport player ( with /p home or /p auto ) in middle of the plot and bug is fixed. :) @boy0001

**Comment by boy0001** [comment]
Set the spawn position in the `PlotSquared/config/worlds.yml` like so:
```YML
worlds:
  plotworld:
    home:
      default: center
      allow-nonmembers: false
```

You can also use a relative coordinate e.g. 1,5
