### ISSUE TITLE
World border

### ISSUE THREAD

**Issue by dzundaza** [IntellectualSites/PlotSquared#1477]
Is there a way to increase border size? If so then how? Thank you

**Comment by RedstoneFuture** [comment]
You don't use WorldBorder?

**Comment by RedstoneFuture** [comment]
Look at this:
https://github.com/IntellectualSites/PlotSquared/wiki/World-reduction#world-border


```
    world:
      max_height: 256
      gamemode: creative
      min_height: 1
      border: false
```
