### ISSUE TITLE
claiming bug in big plots + road bug

### ISSUE THREAD

**Issue by mat41997** [IntellectualSites/PlotSquared#1700]
ss
![2017-08-18_14 49 12](https://user-images.githubusercontent.com/5884000/29459591-b019d04c-8424-11e7-8f27-33d5a1acbce3.png)

files
[files.zip](https://github.com/IntellectualSites/PlotSquared/files/1234448/files.zip)

timings
https://timings.aikar.co/?id=46c10b361aff4a218134c3a19724a10b

**Comment by mat41997** [comment]
![2017-08-18_20 14 58](https://user-images.githubusercontent.com/5884000/29471892-05a9fc12-8452-11e7-95b2-ab1fd6bf5344.png)
and this stupid bug on i changed
```
    road:
      block: '1:6'
      height: 64
      width: 9
```
