### ISSUE TITLE
Teleportation was cancelled after /plot clear|delete

### ISSUE THREAD

**Issue by guuslieben** [IntellectualSites/PlotSquared#1769]
**Debug paste link:** 
https://hastebin.com/umazofetem

**Description of the problem:** 
When a user does `/plot clear` or `/plot delete` while inside the plot, they cannot teleport/warp afterwards. This is only fixed after they relog or if I restart the server (obviously, the first solution is used)

**How to replicate:** 
Stand **inside** a plot and do `/plot clear` or `/plot delete`

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
Which warp- and teleport plugin do you use?

**Comment by guuslieben** [comment]
@RedstoneFuture I am currently using Nucleus

**Comment by RedstoneFuture** [comment]
https://nucleuspowered.org/ For Sponge, right? And with a other teleport and warpplugin?

**Comment by guuslieben** [comment]
As shown in https://hastebin.com/umazofetem . No other teleport/warp plugin(s).
Sponge #2281 (BETA 2610) API 5.2.0
Nucleus 1.1.7 LTS
PlotSquared 3.5.0

```
  SpongeAPI:
    version: 'Optional[5.2.0-SNAPSHOT-c675e80]'
    enabled: true
  SpongeForge:
    version: 'Optional[1.10.2-2281-5.2.0-BETA-2610]'
    enabled: true
  Nucleus:
    version: 'Optional[1.1.7-LTS-S5.1]'
    enabled: true
  PlotSquared:
    version: 'Optional[3.5.0-SNAPSHOT]'
    enabled: true
```
