### ISSUE TITLE
Generation Problems: can't use concrete, wall settings ignored

### ISSUE THREAD

**Issue by mrcoffee1026** [IntellectualSites/PlotSquared#1777]
# Bug report template 

**Debug paste link:** 
https://hastebin.com/kekivuyewe

**Description of the problem:** 
Settings for wall:
`
    wall:
      block: '173'
      block_claimed: '173'
      filling: '173'
      height: 67
`

No walls created....

Attempting to use black concrete instead of coal block for roads between plots:
```
    road:
      width: 2
      height: 63
      block: '251:15'
      offset:
        x: -64
        z: -64

```

Result is a 2 block gap of air between each plot all the way down to bedrock.

**How to replicate:** 
Use default PlotSquared Generator, attempt to use concrete blocks and or specify ANYTHING for the walls.  

**Checklist**:

- [] I included a `/plot debugpaste` link
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
-- updated to latest WorldEdit, FAWE, AND PlotSquared before re-attempting this.
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by mrcoffee1026** [comment]
I need to modify this... I tried a dozen more things and found that I COULD generate walls, but no road?  

These settings had the desired effect, but I have no idea why.  It seems to me that the walls should exist inside the plots themselves?  Apparently I didn't understand that walls are placed OUTSIDE of the plot... and roads around those.  However, the "road" does not generate at all with settings placed this way.  I'm not sure if that's because the "offset" setting causes the roads to cease to exist or not.

The desired effect was: 128 block plots of snow with a 1 block black concrete border... lined up perfectly for map grid use.  Again, the following settings DO provide this... it just shouldn't as best I can tell.  The 2 block concrete "road" is really just walls from each plot, there are no roads.  I thought the walls were not being generated, but on closer inspection I realized there was a layer of snow being tossed onto the bedrock... which I suppose was the unclaimed wall block setting.  The road settings... even though I state to have a 2 block road, I don't think these settings are relevant.  Possibly the offset setting just disables the road but I don't know.

```
    plot:
      height: 64
      size: 126
      filling:
      - '80:0'
      floor:
      - '80:0'
      bedrock: true
      biome: FOREST
      auto_merge: false
      create_signs: true
    wall:
      block: '251:15'
      block_claimed: '251:15'
      filling: '251:15'
      height: 63
    road:
      width: 2
      height: 63
      block: '173:0'
      offset:
        x: -64
        z: -64

```
