### ISSUE TITLE
Removing plots in time

### ISSUE THREAD

**Issue by SirKappa** [IntellectualSites/PlotSquared#1790]
**Good afternoon**, poured out all the questions that are here, I did not find a clear decision on how to make the auto cleaning of rafts exactly according to how the user visited the last time. I need to, if the user did not go, for example 30 days, then his raft was removed without any warnings and buildings there.

**My config**
```
auto-clear:
  auto:
    threshold: -1
    required-plots: -1
    confirmation: false
    days: 30
    worlds: 
    - "*"
    # See: https://github.com/IntellectualSites/PlotSquared/wiki/Plot-analysis
    calibration:
      variety: 0
      variety-sd: 0
      changes: 0
      changes-sd: 0
      faces: 0
      faces-sd: 0
      data-sd: 0
      air: 0
      air-sd: 0
      data: 0
```
**Is this the correct config or not?**
