### ISSUE TITLE
Error /plot debugexec show-expired

### ISSUE THREAD

**Issue by loveGhb** [IntellectualSites/PlotSquared#1864]
**Description of the problem:** 

Error when using **/plot debugexec show-expired**

![image](https://user-images.githubusercontent.com/21294689/35545397-001bcc30-0580-11e8-95a5-90d6db1a310d.png)

Does not automatically delete plots

```
enabled-components:
  plot-expiry: true


auto-clear:
  task1:
    threshold: 1
    required-plots: -1
    confirmation: true
    days: 7
    worlds: 
    - "world"
    # See: https://github.com/IntellectualSites/PlotSquared/wiki/Plot-analysis
    calibration:
      variety: 0
      variety-sd: 0
      changes: 0
      changes-sd: 1
      faces: 0
      faces-sd: 0
      data-sd: 0
      air: 0
      air-sd: 0
      data: 0
```

**How to replicate:** 
/plot debugexec show-expired
Spigot 1.12.2
PlotSquared-Bukkit-18.01.27-8815c83-1959
