### ISSUE TITLE
material names problem in config

### ISSUE THREAD

**Issue by 1425115471** [IntellectualSites/PlotSquared#2131]
Your plug-in is great, and it would be nice if you could support spigot1.13.1

**Comment by mibby** [comment]
Seconding the suggestion. Using material names in the config does not work. Such as standstone_slab in the claimed config.

```
    wall:
      height: 64
      filling: DIRT
      block: STONE_SLAB
      block_claimed: SANDSTONE_SLAB
```
