### ISSUE TITLE
/plot info issues: %size% not working, %seen% is always "Never"

### ISSUE THREAD

**Issue by Dad3** [IntellectualSites/PlotSquared#2285]
# Bug report template 

**Debug paste link:** 

Uploaded a full debug to: https://incendo.org/paste/view/2f6b729ef779443eb1a0e215bb06aba2
**Description of the problem:** 
Havn't tested on 1.13
But on 1.12.2 I am having problems with these placeholders in translation config under plot info: %size% and %seen%
1. The %size% placeholder under plot info in translations config does not work, it always gives %size%.
2. My %seen% placeholder is always giving "Never", even if the player has played before, or is currently online and relogged. (I've seen this work on different servers so might be something I'm doing wrong.)

Screenshot of chat: http://prntscr.com/mqlcat

**How to replicate:** 

Default translations config -> added %size% under plot info.
```yaml
  plot_info: '$1ID: $2%id%$1&-$1Alias: $2%alias%$1&-$1Owner: $2%owner%$1&-$1Biome:
    $2%biome%$1&-$1Can Build: $2%build%$1&-$1Rating: $2%rating%&-$1Seen: $2%seen%&-$1Trusted:
    $2%trusted%$1&-$1Members: $2%members%$1&-$1Denied: $2%denied%$1&-$1Flags: $2%flags%&-$1Size: $2%size%'
  plot_info_footer: $3&m---------&r $1INFO $3&m---------
```
**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
