### ISSUE TITLE
I did translated to br, please add this, i think it will help many people

### ISSUE THREAD

**Issue by CrazyDev** [IntellectualSites/PlotSquared#2782]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server type:
**Select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge
- [] NukkitX

### PlotSquared version: 3.5.0

```
Paste the output here, between the tick marks, replacing this text
```

### Minecraft Version:
**Select one**

- [] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [x] Minecraft 1.12.2
- [x] Minecraft 1.11.2
- [x] Minecraft 1.10.2
- [x] Minecraft 1.9.4
- [x] Minecraft 1.8.8
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:
- [] Minecraft Sponge *specify version*:

### Server build info: 

```
Paste the output here, between the tick marks, replacing this text
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [] WorldEdit version: 

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

[https://pastebin.com/0nCw8Wkm](url)
```yaml
confirm:
  failed_confirm: $2Voce nao tem nenhuma acao pendente para confirmar!
  requires_confirm: '$2Voce tem certeza que deseja executar isto: $1%s$2?&-$2Isto nao pode ser
    desfeito! Se voce tem certeza digite: $1/plot confirm'
move:
  move_success: $4Terreno teleportado com sucesso.
  copy_success: $4Terreno copiado com sucesso.
  requires_unowned: $2A localizacao especificada ja esta ocupada.
set:
  set_attribute: $4Alterado com sucesso, %s0 alterado para %s1
web:
  generating_link: $1Processando terreno...
  generating_link_failed: $2Falha ao gerar o link!
  save_failed: $2Falha ao salvar.
  load_null: $Por favor, use $4/plot load $2para obter a lista de schematics.
  load_failed: $2Falha para carregar o schematic.
  load_list: '$2Para carregar o schematic, use $1/plot load #'
  save_success: $1Salvo com sucesso!
compass:
  compass_target: $4Successfully targeted plot with compass
cluster:
  cluster_available_args: '$1Os seguntes subcomandos estao disponiveis: $4list$2, $4create$2,
    $4delete$2, $4resize$2, $4invite$2, $4kick$2, $4leave$2, $4members$2, $4info$2,
    $4tp$2, $4sethome'
  cluster_list_heading: $2Ha $1%s$2 grupo(s) neste mundo
  cluster_list_element: $2 - $1%s&-
  cluster_intersection: '$2A area proposta sobrepoe a: %s0'
  cluster_added: $4Grupo criado com sucesso.
  cluster_deleted: $4Grupo deletado com sucesso.
  cluster_resized: $4Grupo redimensionado com sucesso.
  cluster_added_user: $4Jogador adicionado com sucesso ao grupo.
  cannot_kick_player: $2Voce nao pode chutar este jogador.
  cluster_invited: '$1Voce foi convidado para seguir o grupo: $2%s'
  cluster_removed: '$1Voce foi removido do grupo: $2%s'
  cluster_kicked_user: $4Jogador chutado com sucesso!
  invalid_cluster: '$1Nome do grupo e invalido: $2%s'
  cluster_not_added: $2Este jogador nao esta adicionado no grupo.
  cluster_cannot_leave: $1Voce deve excluir ou transferir a lideranca antes de sair.
  cluster_added_helper: $4Ajuda do grupo foi adicionada com sucesso.
  cluster_removed_helper: $4Ajuda do grupo foi removida com sucesso.
  cluster_regenerated: $4Regeneracao do grupo iniciada com sucesso.
  cluster_teleporting: $4Teleporte...
  cluster_info: '$1Grupo atual: $2%id%&-$1Nome: $2%name%&-$1Proprietario: $2%owner%&-$1Tamanho:
    $2%size%&-$1Rights: $2%rights%'
border:
  border: $2Voce esta fora da borda do mapa atual.
unclaim:
  unclaim_success: $4Voce cancelou a reinvidicacao do terreno com sucesso.
  unclaim_failed: $2Voce nao pode cancelar a reinvidicacao do terreno.
worldedit masks:
  worldedit_delayed: $2Por favor, aguarde enquanto processamos sua acao no Worldedit...
  worldedit_run: '$2Desculpe pela demora. Executando agora: %s'
  require_selection_in_mask: $2%s da sua selecao nao esta dentro da sua mascara de terreno. Voce so pode editar isso dentro do seu terreno.
  worldedit_volume: $2Voce nao pode selecionar um volume de %current%. O volume maximo que pode ser modificado e %max%.
  worldedit_iterations: $2Voce nao pode iterar %current% vezes. O numero maximo de iteracoes permitido e %max%.
  worldedit_unsafe: $2Acesso para este comando foi bloqueado
  worldedit_bypass: $2&oPara ignorar as restricoes use $4/plot wea
  worldedit_bypassed: $2Restricao do Worldedit foi ignorada.
  worldedit_unmasked: $1Seu Worldedit esta irrestrito.
  worldedit_restricted: $1Seu Worldedit esta restrito.
gamemode:
  gamemode_was_bypassed: $1Voce ignorou o gamemode ($2{gamemode}$1) $1alterado para $2{plot}
height limit:
  height_limit: $1Esta area de terreno tem limite de altura de $2{limit}
records:
  record_play: $2%player $2Comecou a gravar $1%name
  notify_enter: $2%player $2entrou em seu terreno ($1%plot$2)
  notify_leave: $2%player $2deixou seu terreno ($1%plot$2)
swap:
  swap_overlap: $2As areas propostas nao podem se sobrepor.
  swap_dimensions: $2As areas propostas devem ter dimensoes comparaveis.
  swap_syntax: $2/plot swap <id>
  swap_success: $4Terrenos trocados com sucesso.
  started_swap: $2Troca de terrenos iniciada. Voce sera notificado quando terminar.
comment:
  inbox_notification: '%s mensagens nao lidas. Use /plot inbox'
  not_valid_inbox_index: $2Nenhum comentario no indice %s
  inbox_item: $2 - $4%s
  comment_syntax: $2Use /plots comment [X;Z] <%s> <comentario>
  invalid_inbox: '$2Este nao e uma caixa de entrada valida.&-$1Valores aceitados: %s'
  no_perm_inbox: $2Voce nao tem permissao para essa caixa de entrada.
  no_perm_inbox_modify: $2Voce não tem permissão para modificar essa caixa de entrada.
  no_plot_inbox: $2Voce deve permanecer ou fornecer um argumento de terreno.
  comment_removed: $4Comentario deletado com sucesso/s:n$2 - '$3%s$2'
  comment_added: $4Um comentario foi deixado.
  comment_header: $2&m---------&r $1Comentarios $2&m---------&r
  inbox_empty: $2Nenhum comentario.
console:
  not_console: $2Por reacoes de seguranca, este comando so pode ser executado por console.
  is_console: $2Este comando apenas pode ser executado por jogadores.
inventory:
  inventory_usage: '&cUse: &6{usage}'
  inventory_desc: '&cDescricao: &6{desc}'
  inventory_category: '&cCategoria: &6{category}'
clipboard:
  clipboard_set: $2O terreno atual foi copiado para sua area de transferencia, use $1/plot paste$2 para cola-lo
  pasted: $4O terreno selecionado foi colado com sucesso. Foi limpo da sua area de transferencia.
  paste_failed: '$2Falha ao colar selecao. Causa: $2%s'
  no_clipboard: $2Voce nao tem nenhuma selecao na sua area de transferencia.
  clipboard_info: '$2Selecao atual - Terreno ID: $1%id$2, Largura: $1%width$2, Total
    Blocos: $1%total$2'
toggle:
  toggle_enabled: '$2Configuracao ativada: %s'
  toggle_disabled: '$2Configuracao desativada: %s'
blocked command:
  command_blocked: $2Este comando nao esta permitido neste terreno.
done:
  done_already_done: $2Este terreno ja esta marcado como concluido.
  done_not_done: $2Este terreno esta marcado como nao concluido.
  done_insufficient_complexity: $2Este terreno esta tao simples. Por favor, adicione mais detalhes usando o comando.
  done_success: $1Terreno marcado como concluido com sucesso.
  done_removed: $1Voce pode continuar construindo neste terreno.
ratings:
  rating_not_valid: $2Voce precisa especificar um numero entre 1 e 10.
  rating_already_exists: $2Voce ja avaliou este terreno $2%s
  rating_applied: $4Voce avaliou este terreno $2%s
  rating_not_your_own: $2Voce nao pode avaliar seu proprio terreno.
  rating_not_done: $2Voce so pode avaliar os terrenos concluidos.
  rating_not_owned: $2Voce nao pode avaliar este terreno, ele nao possui nenhum proprietario.
tutorial:
  rate_this: $2Avalie este terreno!
  comment_this: '$2Deixe um comentario neste terreno: %s'
economy:
  econ_disabled: $2Economia nao ativada.
  cannot_afford_plot: $2Voce nao pode comprar este terreno. Ele custa $1%s
  not_for_sale: $2Este terreno nao esta a venda.
  cannot_buy_own: $2Voce nao pode comprar seu proprio terreno.
  plot_sold: $4Seu terreno; $1%s0$4, foi vendido para $1%s1$4 por $1$%s2
  cannot_afford_merge: $2Voce nao pode mesclar os terrenos. O valor e $1%s
  added_balance: $1%s $2foi creditado em seu saldo.
  removed_balance: $1%s $2foi retirado do seu saldo.
  removed_granted_plot: $2Voce usou %s concess(ao/oes) de terreno, voce tem $1%s $2restante(s).
setup:
  setup_init: '$1Use: $2/plot setup <value>'
  setup_step: '$3[$1Passo %s0$3] $1%s1 $2- $1Esperando: $2%s2 $1Padrao: $2%s3'
  setup_invalid_arg: '$2%s0 nao e um argumento valido para este passo %s1. para cancelar a configuracao.
    use: $1/plot setup cancel'
  setup_valid_arg: $2Valor $1%s0 $2alterado para %s1
  setup_finished: $4Voce deve se teleportar para o mundo para cria-lo. Caso contrario, voce precisara configurar o gerador manualmente usando o bukkit.yml ou o plug-in de gerenciamento mundial escolhido.
  setup_world_taken: $2%s foi registrado como plotworld
  setup_missing_world: $2Voce precisa especificar um nome de mundo ($1/plot setup &l<world>$1 <generator>$2)&-$1Additional commands:&-$2 - $1/plot setup <value>&-$2 - $1/plot setup back&-$2 - $1/plot setup cancel
  setup_missing_generator: $2Voce precisa especificar um gerador ($1/plot setup <world> &l<generator>&r$2)&-$1Additional commands:&-$2 - $1/plot setup <value>&-$2 - $1/plot setup back&-$2 - $1/plot setup cancel
  setup_invalid_generator: '$2Gerador invalido. Possiveis opcoes: %s'
schematics:
  schematic_too_large: $2O terreno e muito grande para esta acao!
  schematic_missing_arg: '$2Voce precisa especificar um argumento. Possiveis valores: $1test
    <nome>$2 , $1save$2 , $1paste $2, $1exportall'
  schematic_invalid: '$2Este nao e um schematic valido. Causa: $2%s'
  schematic_valid: $2Este nao e um schematic valido.
  schematic_paste_failed: $2Falha ao colar o schematic.
  schematic_paste_success: $4O schamatic foi colado com sucesso!
titles:
  title_entered_plot: '$1Terreno: %world%;%x%;%z%'
  title_entered_plot_sub: $4Proprietario %s
  prefix_greeting: '$1%id%$2> '
  prefix_farewell: '$1%id%$2> '
core:
  task_start: Iniciando tarefa...
  prefix: $3[$1P2$3] $2
  enabled: $1PlotSquared esta ativado.
reload:
  reloaded_configs: $1Traducoes e configuracoes do mundo foram recarregadas.
  reload_failed: $2Falha ao recarregar as configuracoes.
desc:
  desc_set: $2Descricao do terreno foi alterada.
  desc_unset: $2Descricao do terreno foi removida.
  missing_desc: $2Voce precisa especificar uma descricao.
alias:
  alias_set_to: $2Nome do terreno alterado para $1%alias%
  missing_alias: $2Voce precisa especificar um nome.
  alias_too_long: $2O nome deve ser menor que < 50 caracteres de tamanho.
  alias_is_taken: $2Este nome ja esta sendo usado.
position:
  missing_position: '$2Voce precisa especificar uma posicao. Possiveis valores: $1none'
  position_set: $1Home posicao alterado para posicao atual.
  position_unset: $1Home posicao alterado para padrao.
  home_argument: $2Use /plot set home [nenhum]
  invalid_position: $2Este nao e um valor de posicao valido.
cap:
  entity_cap: $2Voce nao tem permissao para spawnar mais monstros.
time:
  time_format: $1%hours%, %min%, %sec%
permission:
  no_schematic_permission: $2Voce nao tem a permissao requerida para usar o schematic $1%s
  no_permission: '$2Voce esta em falta de permissao: $1%s'
  no_permission_event: '$2Voce esta em falta de permissao: $1%s'
  no_plot_perms: $2Voce deve ser o proprietario do terreno para fazer isso.
  cant_claim_more_plots: $2Voce nao pode reinvidicar mais terrenos.
  cant_transfer_more_plots: $2Voce nao pode enviar mais terrenos para este jogador.
  cant_claim_more_plots_num: $2Voce nao pode reinvidicar mais do que $1%s $2terreno(s)
  you_be_denied: $2Voce nao esta permitido entrar neste terreno.
  merge_request_confirm: Pedido de mesclagem de %s
merge:
  merge_not_valid: $2Este pedido de mesclagem nao esta valido mais.
  merge_accepted: $2O pedido de mesclagem de terrenos foi aceito.
  success_merge: $2Terrenos mesclados!
  merge_requested: $2Pedido de mesclagem foi enviado com sucesso.
  no_perm_merge: '$2Voce nao e proprietario deste terreno: $1%plot%'
  no_available_automerge: $2Voce nao possui terrenos adjacentes na direcao especificada ou nao pode mesclar com o tamanho necessario.
  unlink_required: $2Um desvinculo e requirido para fazer isso..
  unlink_impossible: $2Voce so pode desvincular um mega-terreno
  unlink_success: $2Terrenos desvinculados com sucesso.
commandconfig:
  not_valid_subcommand: $2Este nao e um subcomando valido.
  did_you_mean: '$2Voce quis dizer: $1%s'
  name_little: $2%s0 nome e muito curto, $1%s1$2<$1%s3
  no_commands: $2Me desculpe, voce nao tem permissao para utilizar nenhum subcomando.
  subcommand_set_options_header: '$2Possiveis valores: '
  command_syntax: '$1Use: $2%s'
  flag_tutorial_usage: '$1Peca a um administrador para alterar a flag: $2%s'
errors:
  invalid_player_wait: '$2Jogador nao encontrado: $1%s$2, Buscando. Tente novamente em breve.'
  invalid_player: '$2Jogador nao encontrado: $1%s$2.'
  invalid_player_offline: '$2O jogador deve estar online: $1%s.'
  command_went_wrong: $2Alguma coisa deu errado enquanto executa o comando...
  no_free_plots: $2Nao ha terrenos gratuitos disponiveis.
  not_in_plot: $2Voce nao esta dentro de um terreno.
  not_in_cluster: $2Voce deve estar dentro de um cluster de terreno para executar essa acao
  not_in_plot_world: $2Voce nao esta em um mundo de terrenos.
  plotworld_incompatible: $2Os dois mundos devem ser compativeis.
  not_valid_world: $2Esse mundo nao e valido (diferencia maiusculas de minusculas).
  not_valid_plot_world: $2Essa nao e uma area de plotagem valida (diferencia maiusculas de minusculas).
  no_plots: $2Voce nao tem nenhum terreno.
  not_using_plotme: $2Este servidor usa um plugin superior, o $1PlotSquared $2gerenciador de terrenos. Por favor use $1/ps $2ou $1/p2 $2ou $1/plots $2em vez de
  wait_for_timer: $2Um temporizador de setblock esta vinculado ao terreno atual ou a voce. Aguarde o termino.
paste:
  debug_report_created: '$1Enviado debug completo para: $1%url%'
purge:
  purge_success: $4Apaga com sucesso %s terreno(s)
trim:
  trim_in_progress: Uma tarefa de ajusto do mundo ja esta em acao!
  not_valid_hybrid_plot_world: O gerenciador hibrido de terreno e necessario para esta acao.
block list:
  block_list_separater: '$1,$2 '
biome:
  need_biome: $2Voce precisa especificar um bioma.
  biome_set_to: $2Bioma do terreno alterado para $2
teleport:
  teleported_to_plot: $1Voce foi teleportado
  teleported_to_road: $2Voce foi teleportado para estrada.
  teleport_in_seconds: $Teleportando em %s secondo(s). Nao se mova...
  teleport_failed: $2Teleporte canceleado devido ao movimento ou danos.
set block:
  set_block_action_finished: $1O ultimo setblock acabou.
unsafe:
  debugallowunsafe_on: $2Acoes inseguras ativadas.
  debugallowunsafe_off: $2Acoes inseguras desativadas.
debug:
  debug_header: $1Debug Informacao&-
  debug_section: $2>> $1&l%val%
  debug_line: $2>> $1%var%$2:$1 %val%&-
invalid:
  not_valid_data: $2Este nao e um Data ID valido.
  not_valid_block: '$2Este nao e um bloco valido: %s'
  not_allowed_block: '$2Este bloco nao e permitido: %s'
  not_valid_number: '$2Este nao e um numero valido dentro do alcance: %s'
  not_valid_plot_id: $2Este nao e um ID de terreno valido.
  plot_id_form: '$2O ID do terreno deve ser neste formato: $1X;Y $2e.g. $1-5;7'
  not_your_plot: $2Voce nao possui este terreno.
  no_such_plot: $2Nao existe tal terreno.
  player_has_not_been_on: $2Este jogador nao esta em um mundo de terrenos.
  found_no_plots: $2Nao foi encontrado nenhum terreno com sua consulta de pesquisa.
camera:
  camera_started: $2Voce entrou no modo camera em um terreno $1%s
  camera_stopped: $2Voce nao esta mais no modo camera.
need:
  need_plot_number: $2Voce precisa especificar um numero ou nome de um terreno.
  need_block: $2Voce precisa especificar um bloco de um terreno.
  need_plot_id: $2Voce precisa especificar um id de um terreno.
  need_plot_world: $2Voce precisa especificar uma area de um terreno.
  need_user: $2Voce precisa especificar um jogador.
info:
  none: Nenhum
  never: Nunca
  unknown: Desconhecido
  everyone: Todos
  plot_unowned: $2O terreno atual deve ter um proprietario para concluir esta acao.
  plot_info_unclaimed: $2Terreno $1%s$2 nao foi reinvindicado ainda.
  plot_info_header: $3&m---------&r $1INFORMACOES $3&m---------
  plot_info: '$1ID: $2%id%$1&-$1Nome: $2%alias%$1&-$1Proprietario: $2%owner%$1&-$1Bioma:
    $2%biome%$1&-$1Podem construir: $2%build%$1&-$1Avaliacao: $2%rating%&-$1Expira: $2%expires%&-$1Confiados:
    $2%trusted%$1&-$1Membros: $2%members%$1&-$1Negados: $2%denied%$1&-$1Flags: $2%flags%'
  plot_info_footer: $3&m---------&r $1INFORMACOES $3&m---------
  plot_info_trusted: $1Confiados:$2 %trusted%
  plot_info_members: $1Membros:$2 %members%
  plot_info_denied: $1Negados:$2 %denied%
  plot_info_flags: $1Flags:$2 %flags%
  plot_info_biome: $1Bioma:$2 %biome%
  plot_info_rating: $1Avaliacao:$2 %rating%
  plot_info_owner: $1Proprietario:$2 %owner%
  plot_info_id: $1ID:$2 %id%
  plot_info_alias: $1Nome:$2 %alias%
  plot_info_size: $1Tamanho:$2 %size%
  plot_info_expires: $1Expira:$2 %expires%
  plot_user_list: ' $1%user%$2,'
  plot_flag_list: $1%s0:%s1$2
  info_syntax_console: $2/plot info X;Y
working:
  generating_component: $1Iniciado a geracao de compenentes da sua configuracao
  clearing_plot: $2Limpando terreno async .
  clearing_done: $4Limpeza completa! Tomou %sms.
  plot_not_claimed: $2Terreno nao reinvidicado
  plot_is_claimed: $2Este terreno ja foi reinvidicado
  claimed: $4Voce reinvindicou com sucesso o terreno
list:
  comment_list_header_paged: $2(Pagina $1%cur$2/$1%max$2) $1Lista de %amount% comments
  clickable: ' (interativo)'
  area_list_header_paged: $2(Pagina $1%cur$2/$1%max$2) $1Lista de %amount% areas
  plot_list_header_paged: $2(Pagina $1%cur$2/$1%max$2) $1Lista de %amount% terrenos
  plot_list_header: $1Lista de %word% terrenos
  plot_list_item: $2>> $1%id$2:$1%world $2- $1%owner
  plot_list_item_ordered: $2[$1%in$2] >> $1%id$2:$1%world $2- $1%owner
  plot_list_footer: $2>> $1%word% um total de $2%num% $1reinvindicados %plot%.
left:
  left_plot: $2Voce saiu do terreno
chat:
  plot_chat_format: '$2[$1Terreno Chat$2][$1%plot_id%$2] $1%sender%$2: $1%msg%'
  plot_chat_forced: $2Este mundo forca todos usarem o chat do terreno.
  plot_chat_on: $4Plot chat enabled.
  plot_chat_off: $4Chat do terreno desativado.
deny:
  denied_removed: $4Voce removeu este jogador dos jogadores negados.
  denied_added: $4Voce negou este jogador com sucesso.
  denied_need_argument: $2Faltam argumentos. $1/plot negar add <nome> $2ou $1/plot denied remove <nome>
  was_not_denied: $2Este jogador foi negado do terreno.
  you_got_denied: $4Voce foi negado do terreno em que estava, e foi teleportado para o spawn.
kick:
  you_got_kicked: $4Voce foi chutado!
rain:
  need_on_off: '$2Voce precisa especificar um valor. Possiveis valores: $1on$2, $1off'
  setting_updated: $4Voce atualizou as configuracoes com sucesso.
flag:
  flag_key: '$2Chave: %s'
  flag_type: '$2Tipo: %s'
  flag_desc: '$2Desc: %s'
  not_valid_flag: $2Esta nao e uma flag valida.
  not_valid_flag_suggested: '$2Esta nao e uma flag valida. Voce quis dizer: $1%s'
  not_valid_value: $2O valor da flag deve ser alfanumerico.
  flag_not_in_plot: $2O terreno nao tem esta flag.
  flag_not_removed: $2A flag nao pode ser removida.
  flag_not_added: $2A flag nao pode ser adicionada.
  flag_removed: $4Flag removida com sucesso.
  flag_added: $4Flag adicionada com sucesso.
trusted:
  trusted_added: $4Voce confiou com sucesso neste jogador.
  trusted_removed: $4Voce removeu com sucesso a confianca deste jogador.
  was_not_added: $2Este jogador nao recebeu confianca neste terreno.
  plot_removed_user: $1Terreno %s o qual voce foi adicionado foi deletado pela inatividade do proprietario.
member:
  removed_players: $2Foi/foram removido(s) %s jogador(es) deste terreno.
  already_owner: '$2Este jogador ja e proprietario do terreno: %s0'
  already_added: '$2Este jogador ja esta adicionado nesta categoria: %s0'
  member_added: $4Este jogador pode construir enquanto o proprietario estiver online.
  member_removed: $1Voce retirou o membro deste jogador deste terreno.
  member_was_not_added: $2Este jogador nao foi adicionado como um mebro deste terreno.
  plot_max_members: $2Voce nao pode adicionar mais jogadores neste terreno.
owner:
  set_owner: $4Voce alterou o proprietario deste terreno com sucesso.
  now_owner: $4Voce e proprietario do terreno %s
signs:
  owner_sign_line_1: '$1ID: $1%id%'
  owner_sign_line_2: '$1Dono:'
  owner_sign_line_3: $2%plr%
  owner_sign_line_4: $3Adquirido
help:
  help_header: $3&m---------&r $1Terrenos Ajuda $3&m---------
  help_page_header: '$1Categoria: $2%category%$2,$1 Pagina: $2%current%$3/$2%max%$2'
  help_footer: $3&m---------&r $1Terrenos Ajuda $3&m---------
  help_info_item: $1/plot ajuda %category% $3- $2%category_desc%
  help_item: $1%usage% [%alias%]&- $3- $2%desc%&-
  direction: '$1Direcao atual: %dir%'
grants:
  granted_plots: '$1Resultado: $2%s $1concecoes restantes'
  granted_plot: $1Voce concedeu %s0 terreno(s) para $2%s1
  granted_plot_failed: '$1A concessao falhou: $2%s'
'-':
  custom_string: '-'
```

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [] I made sure the bug/error is not caused by any other plugin
- [x] I didn't read but checked everything above.
