### ISSUE TITLE
Problem with auto-delete plots

### ISSUE THREAD

**Issue by Espantonius** [IntellectualSites/PlotSquared#3006]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Without touching anything or deleting anything from files, it doesn't delete the plots that have passed X days.

This is my auto-delete plots configuration: 

```
auto-clear:
  task1:
    threshold: 1
    required-plots: -1
    confirmation: true
    days: 90
    worlds: 
    - "*"
    calibration:
      variety: 0
      variety-sd: 0
      changes: 0
      changes-sd: 1
      faces: 0
      faces-sd: 0
      data-sd: 0
      air: 0
      air-sd: 0
      data: 0
```

I have enabled the option of enabled-components.plot-expiry: true 

### To Reproduce

1. Activate and configure the days to expire the plot.
2. Claim plot and wait for the configured days.
3. View the plot information. 
4. After the limit of days it doesn't delete it.

### Expected behaviour

That the plots are deleted after the configured days.

### Screenshots / Videos

This is a plot that has expired but has not been deleted: https://prnt.sc/12kmbr7
Data player: https://prnt.sc/12kmg6f

### Error log (if applicable)

none

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/fcda7c08d5674374860ebe16328ca469

### PlotSquared Version

PlotSquared version 5.13.11

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

I have previously reported this problem when deleting user information.
I haven't deleted anything for a few days and it's still the same.
The plots continue to count days of disconnection but don't delete them. 

I've tried many settings and none work, even the one on the wiki: https://github.com/IntellectualSites/PlotSquared/wiki/World-reduction#plot-condensation-added-in-275-intensive

I have also tried to change the configuration seen in this area of the wiki https://github.com/IntellectualSites/PlotSquared/wiki/Plot-analysis but when start the server again it restores by default and removes some options.
