### ISSUE TITLE
Invalid plot height when exporting schematic

### ISSUE THREAD

**Issue by CraftCoderr** [IntellectualSites/PlotSquared#3510]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

My goal is to export exactly working area of plot to schematic. My config of plot world looks like this:
```
    world:
      max_height: 110
      gamemode: creative
      min_height: 61
      border: false
```

### To Reproduce

1. Setup max height for plot world
2. Export plot schematic

### Expected behaviour

Schematic contains only blocks between min and max height of plot world.

### Screenshots / Videos

Schematic contains plot blocks between 61 and 110 height and all air above that.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/84524c03b332419181a396ccaea332d7

### PlotSquared Version

6.5.1-SNAPSHOT

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.
