### ISSUE TITLE
Activated TNT Minecarts destroy other entities 

### ISSUE THREAD

**Issue by FMS25** [IntellectualSites/PlotSquared#3837]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

My tester found that you can use TNT minecarts high up and using a launcher to fire TNT into other players plots and blow up entities on the plot boarders.borders

### To Reproduce

1. create a tower/minecart launcher
2. launch tnt onto path or other players plots
3. destroy entities

### Expected behaviour

the TNT to not blow up entities on the path or other players' plots.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/e010046177f7483da1d17056e6134c59

### PlotSquared Version

Activated TNT Minecarts destroy other entities 

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
```yaml
  kill-road-mobs: false
  # Also kill any road mobs that are being ridden, or are leashed
  kill-owned-road-mobs: false
  # Kill items on roads (Stick, Paper, etc.)
  kill-road-items: false
  # Kill vehicles on roads (Boat, Minecart, etc.)
  kill-road-vehicles: false
  # Notify a player of any missed plot comments upon plot entry
  comment-notifier: false
```
Adjust your config.
