### ISSUE TITLE
Plot download ends in exception

### ISSUE THREAD

**Issue by BlockyTheDev** [IntellectualSites/PlotSquared#4056]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

The PlotSquared command `/p download` isn't working on my server, when config is set like on a fresh generation:
```yaml
web:
  url: "https://schem.intellectualsites.com/plots/"
  legacy-webinterface: false
```
When switching to following it is working:
```yaml
web:
  url: "https://schem.intellectualsites.com/plots/"
  legacy-webinterface: true
```

### To Reproduce

1. Execute `/p download`
2. Look into console

### Expected behaviour

Plot download should work.

### Error log (if applicable)

https://gist.github.com/BlockyTheDev/3c52336aa34da34b3a3e58b4b7dfdae1

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/2ed2138a9007497e83ff41df5ee57829

### PlotSquared Version

PlotSquared-6.11.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.
