### ISSUE TITLE
citizens

### ISSUE THREAD

**Issue by runescapejon** [IntellectualSites/PlotSquared#549]
hi i just came cross with a bug i diagnose the problem. and its plotsquard okay so i load up a  plugin called citizens and i make an npc with these commands i make sure that mobs spawnning was on in case next restart goes by  the npc's are gone when i make a private server with just citizens when i restart it the npc was there when i load it up with plotsquard in my private server restart the server the npc are gone any idea how to fix this ?
- /npc create name
- /npc type villager
- /citizens save

**Comment by boy0001** [comment]
Can you try allowing mob spawning? 
```yml
    event:
      spawn:
        breeding: true
        egg: true
        custom: true
```
