### ISSUE TITLE
When clean my plot happens this

### ISSUE THREAD

**Issue by WilliamEstrela** [IntellectualSites/PlotSquared#820]
When clean my plot happens this : http://prntscr.com/9p6gra  How to Disable ?

**Comment by manuelgu** [comment]
Looks like you haven't configured your plot setup properly. Please provide a `/p debugpaste`

**Comment by WilliamEstrela** [comment]
http://hastebin.com/deyaxuloke

**Comment by manuelgu** [comment]
```
worlds:
  plotworld:
    plot:
      height: 64
      biome: FOREST
      size: 32
      filling:
      - null
      auto_merge: false
      bedrock: true
      create_signs: true
      floor:
      - null
    wall:
      filling: '1:0'
      block_claimed: '44:1'
      height: 64
      block: '44:0'
```

You haven't configured your plot setup. Check [the wiki](https://github.com/IntellectualSites/PlotSquared/wiki/Installation#option-1-creating-a-world-with-multiverse) for further information.
