### ISSUE TITLE
Documentation: Manual automagical plot clearing. 

### ISSUE THREAD

**Issue by chamunks** [IntellectualSites/PlotSquared#921]
At some point we need to document [this new feature.](https://github.com/IntellectualSites/PlotSquared/issues/895#event-574222696)

**Comment by boy0001** [comment]
```YAML
clear:
  auto:
    confirmation: false
```
